services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - postgres_db
      - migrate

  migrate:
    build: ./backend
    command: alembic upgrade head
    env_file:
      - .env
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build: ./frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - backend

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email team@theb2r.com --agree-tos --no-eff-email --keep-until-expiring -d theb2r.com -d www.theb2r.com

volumes:
  postgres_data:
  certbot-etc:
  certbot-var:
  web-root:
