services:
  backend:
    build: ./backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - postgres_db
      - migrate

  postgres_db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migrate:
    build: ./backend
    command: alembic upgrade head
    env_file:
      - .env
    depends_on:
      - postgres_db

volumes:
  postgres_data:
