"""add_coordinates_to_coins

Revision ID: 0bab73b5bdd4
Revises: 807754dd8494
Create Date: 2025-09-18 03:27:47.994116

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0bab73b5bdd4'
down_revision = '807754dd8494'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coins', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('coins', sa.Column('longitude', sa.Float(), nullable=True))
    op.create_index(op.f('ix_coins_latitude'), 'coins', ['latitude'], unique=False)
    op.create_index(op.f('ix_coins_longitude'), 'coins', ['longitude'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coins_longitude'), table_name='coins')
    op.drop_index(op.f('ix_coins_latitude'), table_name='coins')
    op.drop_column('coins', 'longitude')
    op.drop_column('coins', 'latitude')
    # ### end Alembic commands ### 