"""CRUD for coin

Revision ID: 4e9f11463453
Revises: a3cac2e6ab24
Create Date: 2025-08-19 14:29:13.740930

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '4e9f11463453'
down_revision = 'a3cac2e6ab24'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 