"""coin model add

Revision ID: 611d7bbf2118
Revises: 862fd4749f27
Create Date: 2025-08-19 08:08:26.339632

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '611d7bbf2118'
down_revision = '862fd4749f27'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 