"""coins

Revision ID: 807754dd8494
Revises: 94f9f8c52712
Create Date: 2025-09-09 11:11:29.331537

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '807754dd8494'
down_revision = '94f9f8c52712'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ar_model_url', sa.String(), nullable=True),
    sa.Column('ar_scale', sa.Float(), nullable=True),
    sa.Column('ar_position_x', sa.Float(), nullable=True),
    sa.Column('ar_position_y', sa.Float(), nullable=True),
    sa.Column('ar_position_z', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coins_id'), 'coins', ['id'], unique=False)
    op.create_index(op.f('ix_coins_name'), 'coins', ['name'], unique=False)
    op.create_index(op.f('ix_coins_symbol'), 'coins', ['symbol'], unique=True)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coins_symbol'), table_name='coins')
    op.drop_index(op.f('ix_coins_name'), table_name='coins')
    op.drop_index(op.f('ix_coins_id'), table_name='coins')
    op.drop_table('coins')
    # ### end Alembic commands ### 