"""add_coin_fields

Revision ID: 830004d91e08
Revises: 94bd0c8564f4
Create Date: 2025-08-20 18:36:15.287556

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '830004d91e08'
down_revision = '94bd0c8564f4'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns as nullable first
    op.add_column('coins', sa.Column('name', sa.String(), nullable=True))
    op.add_column('coins', sa.Column('description', sa.String(), nullable=True))
    op.add_column('coins', sa.Column('icon', sa.String(), nullable=True))
    op.add_column('coins', sa.Column('rarity', sa.String(), nullable=True))
    op.add_column('coins', sa.Column('points', sa.Integer(), nullable=True))
    
    # Fill existing records with default values
    op.execute("UPDATE coins SET name = 'Unknown Achievement' WHERE name IS NULL")
    op.execute("UPDATE coins SET description = 'A mysterious achievement' WHERE description IS NULL")
    op.execute("UPDATE coins SET icon = '🏆' WHERE icon IS NULL")
    op.execute("UPDATE coins SET rarity = 'common' WHERE rarity IS NULL")
    op.execute("UPDATE coins SET points = 10 WHERE points IS NULL")
    
    # Make columns not nullable
    op.alter_column('coins', 'name', nullable=False)
    op.alter_column('coins', 'description', nullable=False)
    op.alter_column('coins', 'icon', nullable=False)
    op.alter_column('coins', 'rarity', nullable=False)
    op.alter_column('coins', 'points', nullable=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coins', 'points')
    op.drop_column('coins', 'rarity')
    op.drop_column('coins', 'icon')
    op.drop_column('coins', 'description')
    op.drop_column('coins', 'name')
    # ### end Alembic commands ### 