"""my second migration

Revision ID: 862fd4749f27
Revises: 94f9f8c52712
Create Date: 2025-08-19 04:39:27.492360

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '862fd4749f27'
down_revision = '94f9f8c52712'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 