"""coin and all coins update

Revision ID: 94bd0c8564f4
Revises: e63d5d998c8d
Create Date: 2025-08-20 07:32:44.865377

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '94bd0c8564f4'
down_revision = 'e63d5d998c8d'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 