"""coin and map model update

Revision ID: a3cac2e6ab24
Revises: c3506830d2a7
Create Date: 2025-08-19 09:12:32.401562

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a3cac2e6ab24'
down_revision = 'c3506830d2a7'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 