"""coin model map model update

Revision ID: c3506830d2a7
Revises: 611d7bbf2118
Create Date: 2025-08-19 08:45:27.716363

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'c3506830d2a7'
down_revision = '611d7bbf2118'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 