"""Add user coin collection table

Revision ID: d17a6f102060
Revises: 0bab73b5bdd4
Create Date: 2025-09-18 21:28:45.220397

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'd17a6f102060'
down_revision = '0bab73b5bdd4'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_coin_collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('coin_id', sa.Integer(), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['coin_id'], ['coins.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_coin_collections_coin_id'), 'user_coin_collections', ['coin_id'], unique=False)
    op.create_index(op.f('ix_user_coin_collections_id'), 'user_coin_collections', ['id'], unique=False)
    op.create_index(op.f('ix_user_coin_collections_user_id'), 'user_coin_collections', ['user_id'], unique=False)
    op.drop_index(op.f('ix_coins_latitude'), table_name='coins')
    op.drop_index(op.f('ix_coins_longitude'), table_name='coins')
    op.drop_column('coins', 'longitude')
    op.drop_column('coins', 'latitude')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coins', sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('coins', sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_coins_longitude'), 'coins', ['longitude'], unique=False)
    op.create_index(op.f('ix_coins_latitude'), 'coins', ['latitude'], unique=False)
    op.drop_index(op.f('ix_user_coin_collections_user_id'), table_name='user_coin_collections')
    op.drop_index(op.f('ix_user_coin_collections_id'), table_name='user_coin_collections')
    op.drop_index(op.f('ix_user_coin_collections_coin_id'), table_name='user_coin_collections')
    op.drop_table('user_coin_collections')
    # ### end Alembic commands ### 